const PWA_KIT_BOT_USER_SESSION = 'pwa-kit-bot-user-session'
const GITHUB_ACTIONS_E2E_SESSION = 'github-actions-e2e-session'
const CI_AVAILABILITY_AVAILABLE = 'available'
const CI_AVAILABILITY_IN_USE = 'in-use'
const ACQUIRE_TARGET_STATUS_SUCCESS = 'ACQUIRE_TARGET_SUCCESS'
const ACQUIRE_TARGET_STATUS_FAILED = 'ACQUIRE_TARGET_FAILED'

const AWS_ACCESS_READ_ONLY = 'READ-ONLY'
const AWS_ACCESS_READ_WRITE = 'READ-WRITE'
const AWS_S3_ERR_NO_SUCH_KEY = 'NoSuchKey'
const AWS_S3_ERR_PRECONDITION_FAILED = 'PreconditionFailedException'

module.exports = {
    PWA_KIT_BOT_USER_SESSION,
    GITHUB_ACTIONS_E2E_SESSION,
    CI_AVAILABILITY_AVAILABLE,
    CI_AVAILABILITY_IN_USE,
    ACQUIRE_TARGET_STATUS_SUCCESS,
    ACQUIRE_TARGET_STATUS_FAILED,
    AWS_ACCESS_READ_ONLY,
    AWS_ACCESS_READ_WRITE,
    AWS_S3_ERR_NO_SUCH_KEY,
    AWS_S3_ERR_PRECONDITION_FAILED
}
